language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"
# deploy 명령어가 실행되기전에 수행
before_deploy:
  - zip -r webp *
  - mkdir -p deploy
  - mv webp.zip deploy/webp.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-build-won
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-delpoy: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-build-won
    key: webp.zip
    bundle_type: zip
    application: freelec-springboot2-webservice
    deploymen_group: freelec-springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - smartwj@naver.com